// Code generated by entc, DO NOT EDIT.

package picture

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Pirika-Pirilala-Popolina-Peperuto/database-system/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PictureURL applies equality check predicate on the "picture_url" field. It's identical to PictureURLEQ.
func PictureURL(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPictureURL), v))
	})
}

// PictureURLEQ applies the EQ predicate on the "picture_url" field.
func PictureURLEQ(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPictureURL), v))
	})
}

// PictureURLNEQ applies the NEQ predicate on the "picture_url" field.
func PictureURLNEQ(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPictureURL), v))
	})
}

// PictureURLIn applies the In predicate on the "picture_url" field.
func PictureURLIn(vs ...string) predicate.Picture {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Picture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPictureURL), v...))
	})
}

// PictureURLNotIn applies the NotIn predicate on the "picture_url" field.
func PictureURLNotIn(vs ...string) predicate.Picture {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Picture(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPictureURL), v...))
	})
}

// PictureURLGT applies the GT predicate on the "picture_url" field.
func PictureURLGT(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPictureURL), v))
	})
}

// PictureURLGTE applies the GTE predicate on the "picture_url" field.
func PictureURLGTE(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPictureURL), v))
	})
}

// PictureURLLT applies the LT predicate on the "picture_url" field.
func PictureURLLT(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPictureURL), v))
	})
}

// PictureURLLTE applies the LTE predicate on the "picture_url" field.
func PictureURLLTE(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPictureURL), v))
	})
}

// PictureURLContains applies the Contains predicate on the "picture_url" field.
func PictureURLContains(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPictureURL), v))
	})
}

// PictureURLHasPrefix applies the HasPrefix predicate on the "picture_url" field.
func PictureURLHasPrefix(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPictureURL), v))
	})
}

// PictureURLHasSuffix applies the HasSuffix predicate on the "picture_url" field.
func PictureURLHasSuffix(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPictureURL), v))
	})
}

// PictureURLEqualFold applies the EqualFold predicate on the "picture_url" field.
func PictureURLEqualFold(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPictureURL), v))
	})
}

// PictureURLContainsFold applies the ContainsFold predicate on the "picture_url" field.
func PictureURLContainsFold(v string) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPictureURL), v))
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProductTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProductInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Picture) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Picture) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Picture) predicate.Picture {
	return predicate.Picture(func(s *sql.Selector) {
		p(s.Not())
	})
}
