// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	fmt "fmt"
	ent "github.com/Pirika-Pirilala-Popolina-Peperuto/database-system/pkg/ent"
	category "github.com/Pirika-Pirilala-Popolina-Peperuto/database-system/pkg/ent/category"
	product "github.com/Pirika-Pirilala-Popolina-Peperuto/database-system/pkg/ent/product"
	uuid "github.com/google/uuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// CategoryService implements CategoryServiceServer
type CategoryService struct {
	client *ent.Client
	UnimplementedCategoryServiceServer
}

// NewCategoryService returns a new CategoryService
func NewCategoryService(client *ent.Client) *CategoryService {
	return &CategoryService{
		client: client,
	}
}

// toProtoCategory transforms the ent type to the pb type
func toProtoCategory(e *ent.Category) (*Category, error) {
	v := &Category{}
	id, err := e.ID.MarshalBinary()
	if err != nil {
		return nil, err
	}
	v.Id = id
	name := e.Name
	v.Name = name
	for _, edg := range e.Edges.Products {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.Products = append(v.Products, &Product{
			Id: id,
		})
	}
	return v, nil
}

// Create implements CategoryServiceServer.Create
func (svc *CategoryService) Create(ctx context.Context, req *CreateCategoryRequest) (*Category, error) {
	category := req.GetCategory()
	m := svc.client.Category.Create()
	categoryName := category.GetName()
	m.SetName(categoryName)
	for _, item := range category.GetProducts() {
		var products uuid.UUID
		if err := (&products).UnmarshalBinary(item.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.AddProductIDs(products)
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoCategory(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements CategoryServiceServer.Get
func (svc *CategoryService) Get(ctx context.Context, req *GetCategoryRequest) (*Category, error) {
	var (
		err error
		get *ent.Category
	)
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetCategoryRequest_VIEW_UNSPECIFIED, GetCategoryRequest_BASIC:
		get, err = svc.client.Category.Get(ctx, id)
	case GetCategoryRequest_WITH_EDGE_IDS:
		get, err = svc.client.Category.Query().
			Where(category.ID(id)).
			WithProducts(func(query *ent.ProductQuery) {
				query.Select(product.FieldID)
			}).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoCategory(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}
	return nil, nil

}

// Update implements CategoryServiceServer.Update
func (svc *CategoryService) Update(ctx context.Context, req *UpdateCategoryRequest) (*Category, error) {
	category := req.GetCategory()
	var categoryID uuid.UUID
	if err := (&categoryID).UnmarshalBinary(category.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m := svc.client.Category.UpdateOneID(categoryID)
	categoryName := category.GetName()
	m.SetName(categoryName)
	for _, item := range category.GetProducts() {
		var products uuid.UUID
		if err := (&products).UnmarshalBinary(item.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.AddProductIDs(products)
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoCategory(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements CategoryServiceServer.Delete
func (svc *CategoryService) Delete(ctx context.Context, req *DeleteCategoryRequest) (*emptypb.Empty, error) {
	var err error
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	err = svc.client.Category.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements CategoryServiceServer.List
func (svc *CategoryService) List(ctx context.Context, req *ListCategoryRequest) (*ListCategoryResponse, error) {
	var (
		err      error
		entList  []*ent.Category
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Category.Query().
		Order(ent.Desc(category.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := uuid.ParseBytes(bytes)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(category.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListCategoryRequest_VIEW_UNSPECIFIED, ListCategoryRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListCategoryRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			WithProducts(func(query *ent.ProductQuery) {
				query.Select(product.FieldID)
			}).
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		var pbList []*Category
		for _, entEntity := range entList {
			pbEntity, err := toProtoCategory(entEntity)
			if err != nil {
				return nil, status.Errorf(codes.Internal, "internal error: %s", err)
			}
			pbList = append(pbList, pbEntity)
		}
		return &ListCategoryResponse{
			CategoryList:  pbList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}
